account/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import (login, logout, password_reset,
        password_reset_done, password_reset_confirm, password_reset_complete)

from account import views

urlpatterns = patterns('',
    #TODO Disable Registration Setting
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),

    url(r'^password/reset/(?P<uidb36>.+)/(?P<token>.+)/$', password_reset_confirm,
           {"template_name": "reset_conf.html",
            "current_app": "account",
            "post_reset_redirect": "/account/password/complete/"},
        name="password_reset_confirm"),
    url(r'^password/reset/$', password_reset, 
           {"template_name": "reset.html",
            "email_template_name": "reset_mail.html",
            "subject_template_name": "reset_subject.txt",
            "current_app": "account",
            "from_email": "triage@ironowl.io", #TODO Import email address
            "post_reset_redirect": "/account/password/sent/"},
        name="reset"),
    url(r'^password/sent/$', password_reset_done, {"template_name": "reset_ok.html"}, name="password_done"),
    url(r'^password/complete/$', password_reset_complete, {"template_name": "reset_complete.html"}, name="password_complete"),
)

task/urls.py
from django.conf.urls import patterns, url

import receivers

import task.views as TaskViews

urlpatterns = patterns('',
    url(r'^dashboard/$', TaskViews.dashboard, name="dashboard"),
    url(r'^calendar/$', TaskViews.calendar, name="calendar"),
    url(r'^housekeeping/$', TaskViews.housekeeping, name="housekeeping"),
    url(r'^preferences/$', TaskViews.preferences, name="preferences"),

    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/$', TaskViews.view_task, name="view_task"),
    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/edit/$', TaskViews.edit_task, name="edit_task"),
    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/link/$', TaskViews.link_task, name="link_task"),
    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/complete/$', TaskViews.complete_task, name="complete_task"),
    url(r'^(?P<username>\w+)/task/new/$', TaskViews.new_task, name="new_task"),

    url(r'^(?P<username>\w+)/settings/triage/new/$', TaskViews.add_triage_category, name="add_triage_category"),
    url(r'^(?P<username>\w+)/settings/triage/(?P<triage_category_id>\d+)/edit/$', TaskViews.edit_triage_category, name="edit_triage_category"),
    url(r'^(?P<username>\w+)/settings/triage/$', TaskViews.list_triage_category, name="list_triage_category"),

    url(r'^(?P<username>\w+)/list/new/$', TaskViews.add_tasklist, name="add_tasklist"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/edit/$', TaskViews.edit_tasklist, name="edit_tasklist"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/delete/$', TaskViews.delete_tasklist, name="delete_tasklist"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/$', TaskViews.list_milestones, name="list_milestones"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/(?P<milestone_id>\d+)/$', TaskViews.view_milestone, name="view_milestone"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/new/$', TaskViews.new_milestone, name="new_milestone"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/(?P<milestone_id>\d+)/edit/$', TaskViews.edit_milestone, name="edit_milestone"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/$', TaskViews.view_tasklist, name="view_tasklist"),

    url(r'^(?P<username>\w+)/$', TaskViews.profile, name="profile"),
)

triage/urls.py
from django.conf.urls import patterns, include, url
from task import views as TaskViews

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TaskViews.list_tasks, name="home"),
    url(r'^account/', include("account.urls", namespace="account", app_name="account")),
    url(r'^', include("task.urls", namespace="task", app_name="task")),
)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.html import escape

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Fieldset, Submit
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=30)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput(), label="Password")
    password2 = forms.CharField(widget=forms.PasswordInput(), label="Confirm password")

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        # django-crispy-forms
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
        self.helper.layout = Layout(
            Div(
                Div(
                    Fieldset('Basic',
                        'username',
                        'first_name',
                        'last_name',
                        'email',
                    ),
                    css_class="col-lg-6"),
                Div(
                    Fieldset('Password',
                        'password1',
                        'password2',
                    ),
                    css_class="col-lg-6"
                ),
                css_class="row"
            ),
            FormActions(
                Submit('register', 'Register'),
            )
        )

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).count() > 0:
            raise forms.ValidationError('This username has already been registered.')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).count() > 0:
            raise forms.ValidationError('This email has already been registered.')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if not password2:
            raise forms.ValidationError("You must confirm your password.")
        if password1 != password2:
            raise forms.ValidationError("Your passwords do not match.")
        return password2

account/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.debug import sensitive_post_parameters

from account.forms import RegistrationForm
from account.signals import user_registered

@sensitive_post_parameters('password', 'password2')
def register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('task:profile', kwargs={"username": request.user.username}))

    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        newUser = {
            "username": form.cleaned_data["username"],
            "first_name": form.cleaned_data["first_name"],
            "last_name": form.cleaned_data["last_name"],
            "email": form.cleaned_data["email"],
        }
        user = User.objects.create(**newUser)
        user.set_password(form.cleaned_data["password2"])
        user.save()
        user_registered.send(sender=request.POST, post=request.POST, new_user=user, request=request)

        auth_user = authenticate(username=user.username, password=form.cleaned_data["password2"])
        if auth_user:
            login(request, auth_user)
        return HttpResponseRedirect(request.POST.get('next', '/'))

    return render(request, "register.html", {
        'form': form,
    })

account/templates/login.html
{% extends "base/base.html" %}

{% block title %}Login{% endblock %}

{% block navbar %}{% endblock %}
{% block body-class %}body-login{% endblock %}
{% block content-class %}container-login{% endblock %}
{% block content %}
<style>
    input {
        margin-bottom: 8px;
    }
</style>
<div class="col-md-4 col-md-offset-4">
    <h1>Triage Beta</h1>
    <h2>A todo manager for the disaster that is your day.</h2>
    <p>Existing users please log in.</p>
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title">Warning</h3>
        </div>
        <div class="panel-body">
            This instance of Triage is hosted on the unstable development branch; you may encounter unexpected behaviour.
        </div>
    </div>
    {% if form.errors %}
        {% for message in form.non_field_errors %}
            <div class="alert alert-warning">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <form action="{% url 'account:login' %}" method="post" role="form">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" class="form-control" placeholder="Username" autofocus="" required />

        <label for="password">Password:</label>
        <input type="password" name="password" class="form-control" placeholder="Password" required />
        <input type="hidden" name="next" value="{% if next %}{{ next }}{% else %}/{% endif %}" />

        <button type="submit" class="btn btn-primary btn-block">Log in</button>
        <a class="btn btn-block btn-info" href="{% url 'account:register' %}">Register</a>
    </form>
    <a href="{% url 'account:reset' %}">Forgotten password?</a>
</div>
{% endblock %}

account/templates/register.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}
{% block content %}
   <div class="row-fluid">
    <h1>Register</h1>
    <p>Begin handling the disaster that is your day by creating an account...</p>
    <hr />
    <div class="alert alert-info"><b>Beta Testing</b><br/>Please note that Triage is still under active development, there will be incomplete or non-functional components and occasional bugs.</div>
      <form action="{% url 'account:register' %}" method="post">
          {% crispy form %}
      </form>
  </div>
{% endblock %}

account/templates/reset.html
{% extends "base/base.html" %}

{% block title %}Reset Password{% endblock %}
{% block content %}
   <div class="row-fluid">
    <h1>Reset Password</h1>
    <hr />
      <form action="{% url 'account:reset' %}" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input class="btn btn-primary" type="submit" name="submit" />
      </form>
  </div>
{% endblock %}

account/templates/reset_complete.html
{% extends "base/base.html" %}

{% block title %}Reset Password Complete{% endblock %}
{% block content %}
   <div class="row-fluid">
    <h1>Reset Password Complete</h1>
    <hr />
    <p>Your password has been successfully set. You are welcome to log in now.</p>
    <p><a href="{% url 'account:login' %}">Log in</a></p>
  </div>
{% endblock %}

account/templates/reset_conf.html
{% extends "base/base.html" %}

{% block title %}Reset Password{% endblock %}
{% block content %}
   <div class="row-fluid">
    <h1>Reset Password</h1>
    <hr />
      <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input class="btn btn-primary" type="submit" name="submit" />
      </form>
  </div>
{% endblock %}

account/templates/reset_mail.html
Hi {{ user.first_name }}!
Someone has requested a password reset on triage.ironowl.io for email {{ user.email }}.
To change your password please follow the link below:

https://triage.ironowl.io/{% url 'account:password_reset_confirm' uid token %}

In case you've forgotten, your username is {{ user.username }}.

If you did not request this e-mail you are safe to just ignore it.

Thanks,
Triage Team

account/templates/reset_ok.html
{% extends "base/base.html" %}

{% block title %}Reset Password{% endblock %}
{% block content %}
   <div class="row-fluid">
    <h1>Reset Password</h1>
    <hr />
    <p>Password reset mail sent! Please check your inbox (don't forgot to check your spam folder).</p>
  </div>
{% endblock %}