account/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import (login, logout, password_reset,
        password_reset_done, password_reset_confirm, password_reset_complete)

from account import views

urlpatterns = patterns('',
    #TODO Disable Registration Setting
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),

    url(r'^password/reset/(?P<uidb36>.+)/(?P<token>.+)/$', password_reset_confirm,
           {"template_name": "reset_conf.html",
            "current_app": "account",
            "post_reset_redirect": "/account/password/complete/"},
        name="password_reset_confirm"),
    url(r'^password/reset/$', password_reset, 
           {"template_name": "reset.html",
            "email_template_name": "reset_mail.html",
            "subject_template_name": "reset_subject.txt",
            "current_app": "account",
            "from_email": "triage@ironowl.io", #TODO Import email address
            "post_reset_redirect": "/account/password/sent/"},
        name="reset"),
    url(r'^password/sent/$', password_reset_done, {"template_name": "reset_ok.html"}, name="password_done"),
    url(r'^password/complete/$', password_reset_complete, {"template_name": "reset_complete.html"}, name="password_complete"),
)

task/urls.py
from django.conf.urls import patterns, url

import receivers

import task.views as TaskViews

urlpatterns = patterns('',
    url(r'^dashboard/$', TaskViews.dashboard, name="dashboard"),
    url(r'^calendar/$', TaskViews.calendar, name="calendar"),
    url(r'^housekeeping/$', TaskViews.housekeeping, name="housekeeping"),
    url(r'^preferences/$', TaskViews.preferences, name="preferences"),

    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/$', TaskViews.view_task, name="view_task"),
    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/edit/$', TaskViews.edit_task, name="edit_task"),
    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/link/$', TaskViews.link_task, name="link_task"),
    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/complete/$', TaskViews.complete_task, name="complete_task"),
    url(r'^(?P<username>\w+)/task/new/$', TaskViews.new_task, name="new_task"),

    url(r'^(?P<username>\w+)/settings/triage/new/$', TaskViews.add_triage_category, name="add_triage_category"),
    url(r'^(?P<username>\w+)/settings/triage/(?P<triage_category_id>\d+)/edit/$', TaskViews.edit_triage_category, name="edit_triage_category"),
    url(r'^(?P<username>\w+)/settings/triage/$', TaskViews.list_triage_category, name="list_triage_category"),

    url(r'^(?P<username>\w+)/list/new/$', TaskViews.add_tasklist, name="add_tasklist"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/edit/$', TaskViews.edit_tasklist, name="edit_tasklist"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/delete/$', TaskViews.delete_tasklist, name="delete_tasklist"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/$', TaskViews.list_milestones, name="list_milestones"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/(?P<milestone_id>\d+)/$', TaskViews.view_milestone, name="view_milestone"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/new/$', TaskViews.new_milestone, name="new_milestone"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/(?P<milestone_id>\d+)/edit/$', TaskViews.edit_milestone, name="edit_milestone"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/$', TaskViews.view_tasklist, name="view_tasklist"),

    url(r'^(?P<username>\w+)/$', TaskViews.profile, name="profile"),
)

triage/urls.py
from django.conf.urls import patterns, include, url
from task import views as TaskViews

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TaskViews.list_tasks, name="home"),
    url(r'^account/', include("account.urls", namespace="account", app_name="account")),
    url(r'^', include("task.urls", namespace="task", app_name="task")),
)

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %} | Triage</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/custom.css" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet">
    <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/static/img/icon.png" />
</head>

<body class="{% block body-class %}{% endblock %}">
    <div id="wrapper">
        {% block navbar %}
        <nav class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="glyphicon glyphicon-collapse-down"></span>
                    </button>
                <a class="navbar-brand" href="/">Triage</a>
                </div>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        {% if user.is_authenticated %}
                            <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle"><span class="glyphicon glyphicon-list"></span> Task Lists <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    {% for tasklist in user.tasklists.all|dictsort:"name" %}
                                        <li><a href="{% url 'task:view_tasklist' tasklist.user.username tasklist.slug %}">{{ tasklist.name }}</a></li>
                                    {% endfor %}
                                    <li class="divider"></li>
                                    <li><a href="{% url 'task:add_tasklist' user.username %}">New...</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'task:dashboard' %}"><span class="glyphicon glyphicon-th"></span> Dashboard</a></li>
                            <li><a href="{% url 'task:calendar' %}"><span class="glyphicon glyphicon-calendar"></span> Calendar</a></li>
                            <li><a href="{% url 'task:housekeeping' %}"><span class="glyphicon glyphicon-leaf"></span> Housekeeping</a></li>

                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li class="dropdown">
                                <a class="dropdown-toggle" href="#" data-toggle="dropdown"><div class="btn btn-xs btn-success"><span class="glyphicon glyphicon-plus-sign"></span> Task <strong class="caret"></strong></div></a>
                                <div class="dropdown-menu dropdown-menu-form">
                                    {% include 'task/includes/quick_add.html' %}
                                </div>
                            </li>
                            <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">{{ user.username }} <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'task:profile' user.username %}">Profile</a></li>
                                <li class="divider"></li>
                                <li><b><span class="glyphicon glyphicon-cog"></span> Settings</b></li>
                                <li><a href="{% url 'task:preferences' %}">Preferences</a></li>
                                <li><a href="{% url 'task:list_triage_category' user.username %}">Triages</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'account:logout' %}">Logout</a></li>
                            </ul>
                            </li>
                        {% else %}
                            <li><a href="{% url 'account:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% endblock %}
        <div id="content-head-outer" class="{% block content-head-class %}{% endblock %}">
            <div id="content-head">
                {% block content-head %}{% endblock %}
            </div>
        </div>
        <div id="content-outer" class="{% block content-class %}{% endblock %}">
            <div class="container">
                <div id="content">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-info alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                {{ message|safe }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        <div class="push"></div>
    </div>
    <footer>
        <div class="text-center">
            <b><span class="ironowl"><a href="http://ironowl.io">IO</a></span></b>
        </div>
    </footer>
</body>
</html>