task/urls.py
from django.conf.urls import patterns, url

import receivers

import task.views as TaskViews

urlpatterns = patterns('',
    url(r'^dashboard/$', TaskViews.dashboard, name="dashboard"),
    url(r'^calendar/$', TaskViews.calendar, name="calendar"),
    url(r'^housekeeping/$', TaskViews.housekeeping, name="housekeeping"),
    url(r'^preferences/$', TaskViews.preferences, name="preferences"),

    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/$', TaskViews.view_task, name="view_task"),
    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/edit/$', TaskViews.edit_task, name="edit_task"),
    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/link/$', TaskViews.link_task, name="link_task"),
    url(r'^(?P<username>\w+)/task/(?P<task_id>\d+)/complete/$', TaskViews.complete_task, name="complete_task"),
    url(r'^(?P<username>\w+)/task/new/$', TaskViews.new_task, name="new_task"),

    url(r'^(?P<username>\w+)/settings/triage/new/$', TaskViews.add_triage_category, name="add_triage_category"),
    url(r'^(?P<username>\w+)/settings/triage/(?P<triage_category_id>\d+)/edit/$', TaskViews.edit_triage_category, name="edit_triage_category"),
    url(r'^(?P<username>\w+)/settings/triage/$', TaskViews.list_triage_category, name="list_triage_category"),

    url(r'^(?P<username>\w+)/list/new/$', TaskViews.add_tasklist, name="add_tasklist"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/edit/$', TaskViews.edit_tasklist, name="edit_tasklist"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/delete/$', TaskViews.delete_tasklist, name="delete_tasklist"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/$', TaskViews.list_milestones, name="list_milestones"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/(?P<milestone_id>\d+)/$', TaskViews.view_milestone, name="view_milestone"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/new/$', TaskViews.new_milestone, name="new_milestone"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/milestones/(?P<milestone_id>\d+)/edit/$', TaskViews.edit_milestone, name="edit_milestone"),
    url(r'^(?P<username>\w+)/(?P<listslug>[-\w]+)/$', TaskViews.view_tasklist, name="view_tasklist"),

    url(r'^(?P<username>\w+)/$', TaskViews.profile, name="profile"),
)

triage/urls.py
from django.conf.urls import patterns, include, url
from task import views as TaskViews

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TaskViews.list_tasks, name="home"),
    url(r'^account/', include("account.urls", namespace="account", app_name="account")),
    url(r'^', include("task.urls", namespace="task", app_name="task")),
)

task/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.db.models.fields.related import ForeignKey
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.defaultfilters import slugify
from django.utils.timezone import utc

import task.models as TaskModels
import task.forms as TaskForms
import task.utils as TaskUtils
import task.events as TaskEvents
import event.utils as EventUtils

@login_required
def list_tasks(request):
    tasklists = request.user.tasklists.all()
    return render(request, "task/list.html", {"tasklists": tasklists})

@login_required
def new_task(request, username):
    listslug = request.GET.get("tasklist", None)
    if listslug:
        tasklist = get_object_or_404(TaskModels.TaskList, slug=listslug, user__username=username)
        if tasklist.has_edit_permission(request.user.pk):
            return edit_task(request, username, None, tasklist.pk)
        else:
            return HttpResponseRedirect(reverse('home'))
    else:
        return edit_task(request, username, None, None)

def view_tasklist(request, username, listslug):
    tasklist = get_object_or_404(TaskModels.TaskList, slug=listslug, user__username=username)
    if not tasklist.has_view_permission(request.user.pk):
        return HttpResponseRedirect(reverse('home'))
    calendar = TaskUtils.calendarize(None, 30, tasklist.pk)
    edit_permission = tasklist.has_edit_permission(request.user.pk)
    return render(request, "task/tasklist.html", {"tasklist": tasklist,
                                                  "calendar": calendar,
                                                  "recently_added": tasklist.recently_added(limit=5),
                                                  "recently_closed": tasklist.recently_closed(limit=5),
                                                  "upcoming_week": tasklist.upcoming_tasks(days=7),
                                                  "upcoming_month": tasklist.upcoming_tasks(offset=7, days=30),
                                                  "overdue": tasklist.overdue_tasks,
                                                  "edit_permission": edit_permission})

def view_task(request, username, task_id):
    task = get_object_or_404(TaskModels.Task, tasklist__user__username=username, _id=task_id)
    if not task.has_view_permission(request.user.pk):
        return HttpResponseRedirect(reverse('home'))
    history = EventUtils._get_history(task)
    edit_permission = task.has_edit_permission(request.user.pk)
    return render(request, "task/view.html", {"task": task,
                                              "history": history,
                                              "edit_permission": edit_permission})

def view_milestone(request, username, listslug, milestone_id):
    milestone = get_object_or_404(TaskModels.TaskMilestone, tasklist__user__username=username, pk=milestone_id)
    edit_permission = milestone.has_edit_permission(request.user.pk)

    if not milestone.has_view_permission(request.user.pk):
        return HttpResponseRedirect(reverse('home'))
    return render(request, "task/milestone.html", {"milestone": milestone,
                                                  "edit_permission": edit_permission})


@login_required
def edit_task(request, username, task_id, tasklist_id=None):

    if tasklist_id:
        tasklist = get_object_or_404(TaskModels.TaskList, pk=tasklist_id)
        if not tasklist.has_edit_permission(request.user.pk):
            return HttpResponseRedirect(reverse('home'))

    milestone_id = None
    milestone = request.GET.get("milestone", None)
    if milestone:
        milestone = get_object_or_404(TaskModels.TaskMilestone, tasklist__user__username=username, pk=milestone)
        if not milestone.has_edit_permission(request.user.pk):
            return HttpResponseRedirect(reverse('home'))
        milestone_id = milestone.pk

    task = None
    if task_id:
        task = get_object_or_404(TaskModels.Task, tasklist__user__username=username, _id=task_id)
        if not task.has_edit_permission(request.user.pk):
            return HttpResponseRedirect(reverse('home'))
        tasklist_id = task.tasklist_id

        if task.milestone:
            milestone_id = task.milestone.pk


    form = TaskForms.TaskForm(
               request.user.id,
               tasklist_id,
               request.POST.get('form_type', None),
               request.POST or None,
               initial={
                   'tasklist': tasklist_id,
                   'milestone': milestone_id
               },
               instance=task)

    if form.is_valid():
        # Don't really like hitting the database for a copy of this but it will
        # more than do for now
        if task:
            original = TaskModels.Task.objects.get(pk=task.pk)
        else:
            original = None

        task = form.save(commit=False)
        task.save()

        # Save the history, make a CreationEvent if Task is new
        if not original:
            TaskEvents.CreationEvent(request, task)
        TaskEvents.FieldChange(request, original, task)

        # Display a message if this was sent from quick_add
        if request.POST.get('quick', None):
            url = reverse('task:view_task', kwargs={"username": task.tasklist.user.username,
                                                    "task_id": task.local_id})
            msg = "Task <b><a class='alert-link' href='" + url + "'>#" + str(task.local_id) + ": " + task.name + "</a></b> added successfully."
            messages.add_message(request, messages.SUCCESS, msg, extra_tags='safe')

        redirect_to = request.POST.get('next', "/")
        return HttpResponseRedirect(redirect_to)

    redirect_to = request.GET.get('next', "/")
    return render(request, "task/changetask.html", {"form": form,
                                                    "task": task,
                                                    "next": redirect_to})

@login_required
def complete_task(request, username, task_id):
    task = get_object_or_404(TaskModels.Task, tasklist__user__username=username, _id=task_id)
    if not task.has_edit_permission(request.user.pk):
        return HttpResponseRedirect(reverse('home'))

    # Don't really like hitting the database for a copy of this but it will
    # more than do for now
    if task:
        original = TaskModels.Task.objects.get(pk=task.pk)
    else:
        original = None

    task.completed = True
    task.completed_date = datetime.datetime.utcnow().replace(tzinfo=utc)
    task.save()

    # Save the history
    TaskEvents.FieldChange(request, original, task)

    redirect_to = request.GET.get('next', "/")
    return HttpResponseRedirect(redirect_to)

@login_required
def link_task(request, username, task_id):
    task = get_object_or_404(TaskModels.Task, tasklist__user__username=username, _id=task_id)
    if not task.has_edit_permission(request.user.pk):
        return HttpResponseRedirect(reverse('home'))

    form = TaskForms.TaskLinkForm(request.user.id, request.POST or None,
            initial={'from_task': task.pk})

    if form.is_valid():
        link = form.save()
        TaskEvents.LinkChange(request, link)
        return HttpResponseRedirect(reverse('task:view_task', kwargs={"username": task.tasklist.user.username,
                                                                      "task_id": task.local_id}))
    return render(request, "task/changelink.html", {"form": form})

@login_required
def add_tasklist(request, username):
    return edit_tasklist(request, username)

@login_required
def edit_tasklist(request, username=None, listslug=None):
    tasklist = None
    if username and listslug:
        tasklist = get_object_or_404(TaskModels.TaskList, slug=listslug, user__username=username)
        if not tasklist.has_edit_permission(request.user.pk):
            return HttpResponseRedirect(reverse('home'))

    form = TaskForms.TaskListForm(request.user.id, request.POST or None, instance=tasklist)
    if form.is_valid():
        tasklist = form.save(commit=False)

        # Update the redirect (if needed) if the slug will be changed!
        redirect_to = request.POST.get('next', "/")
        if tasklist.id and tasklist.slug != slugify(form.cleaned_data["name"]):
            if tasklist.slug in redirect_to:
                redirect_to = redirect_to.replace(tasklist.slug, slugify(form.cleaned_data["name"]))

        if not form.instance.pk:
            # New list, attach user
            tasklist.user = request.user
            tasklist.slug = slugify(form.cleaned_data["name"])
        tasklist.save()

        return HttpResponseRedirect(redirect_to)

    redirect_to = request.GET.get('next', "/")
    return render(request, "task/changelist.html", {"form": form,
                                                    "tasklist": tasklist,
                                                    "next": redirect_to})

@login_required
def delete_tasklist(request, username=None, listslug=None):
    tasklist = None
    if username and listslug:
        tasklist = get_object_or_404(TaskModels.TaskList, slug=listslug, user__username=username)
        if not tasklist.has_edit_permission(request.user.pk):
            return HttpResponseRedirect(reverse('home'))

    form = TaskForms.TaskListDeleteForm(request.user.id, tasklist.pk, request.POST or None)
    if form.is_valid():
        transfer_to = form.cleaned_data["tasklist_transfer"]

        # Transfer Tasks and Delete
        # TODO Currently assuming user has right to move all tasks in a list
        # NOTE This is a fair assumption given the current permission model
        for task in TaskModels.Task.objects.filter(tasklist__pk=tasklist.pk):
            task.tasklist = transfer_to
            task.save()

templates/task/changelink.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add or Edit Task Link{% endblock %}

{% block content-head-class %}head-dark{% endblock %}
{% block content-head %}
<a style="color: white;" title="Return Home" href="{% url 'home' %}">
    <div style="float: left;" class="col-md-1 text-center">
        <h3><span class="glyphicon glyphicon-chevron-left pull-right"></span></h3>
    </div>
</a>
<div class="container">
    <div class="row">
        <h1>Add or Edit Task Link</h1>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="alert alert-danger">
    <strong>Sorry!</strong><br/>
    Task Linking is an incomplete feature! Please come back another day.
</div>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit"></input>
</form>
{% endblock %}

templates/task/default_due_time_js.html
<script type="text/javascript">
    {% if user.triageuser.default_due_time %}
        $(document).ready(function() {
            $('.timeinput').focus(function(){
                if($(".timeinput").prop("value") == ""){
                    // Set the time if no already set to a value
                    $('.timeinput').val("{{ user.triageuser.default_due_time|date:"H:i" }}");
                }
            });
        });
    {% endif %}
</script>

templates/task/tasklist.html
{% extends "base/base.html" %}

{% block title %}{% if not edit_permission %}{{ tasklist.user.username }}/{% endif %}{{ tasklist.name }}{% endblock %}

{% block content-head-class %}head-dark{% endblock %}
{% block content-head %}
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.4.0/moment.min.js" type="text/javascript"></script>
<div class="container">
    <div class="row">
        <div class="col-sm-8">
            <h1>{% if not edit_permission %}<a href="{% url 'task:profile' tasklist.user.username %}">{{ tasklist.user.username }}</a> / {% endif %}{{ tasklist.name }}</h1>
            <p>{{ tasklist.description }}</p>
        </div>
        <div class="col-sm-4">
            {% if edit_permission %}
            <div class="btn-group pull-right">
                <a class="btn btn-success" href="{% url 'task:new_task' tasklist.user.username %}?tasklist={{ tasklist.slug }}&next={{ current_url }}"><span class="glyphicon glyphicon-plus"></span> New Task</a>
                <a class="btn btn-warning" href="{% url 'task:edit_tasklist' tasklist.user.username tasklist.slug %}?next={{ current_url }}"><span class="glyphicon glyphicon-pencil"></span></a>
                <a class="btn btn-danger" href="{% url 'task:delete_tasklist' tasklist.user.username tasklist.slug %}?next={{ current_url }}"><span class="glyphicon glyphicon-remove"></span></a>
            <a class="btn btn-info" href="{% url 'task:list_milestones' tasklist.user.username tasklist.slug %}"><span class="glyphicon glyphicon-cog"></span> Milestones</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<script type="text/javascript">
    function humanize(timestamp){
        return moment(timestamp).fromNow();
    };
    $(document).ready(function(){
        $(".human_date").html(function() {
            return humanize($(this).html());
        });
        $(".due_date").html(function() {
            return humanize($(this).html());
        });
    });
</script>

<div class="row">
    {% include "task/includes/calendar.html" %}
</div>

<div class="row">
    <div class="col-sm-2">
        <h2 class="text-center">Status</h2>
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th class="col-md-6 text-center">Open</th>
                    <th class="col-md-6 text-center">Closed</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="text-center task-counter">{{ tasklist.num_incomplete }}</td>
                    <td class="text-center task-counter">{{ tasklist.num_complete }}</td>
                </tr>
                {% for triage in tasklist.user.triages.all %}
                    <tr>
                        <td class="label_light-right text-center" style="border-right-color:#{{ triage.bg_colour }}">{{ triage.open_tasks.count }}</td>
                        <td class="label_light text-center" style="border-left-color:#{{ triage.bg_colour }}">{{ triage.closed_tasks.count }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-sm-10">
        {% include "task/includes/dash.html" %}
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-10 col-sm-push-2">
        <h2>All Open Tasks</h2>
        {% if tasklist.num_incomplete > 0 %}
            <table class="table table-hover table-condensed">
                <thead>
                    <tr>
                        <th class="col-md-1 text-center">#</th>
                        <th class="col-md-7">Task</th>
                        <th class="col-md-2">Due</th>
                        <th class="col-md-1"></th>
                    </tr>
                </thead>
                <tbody>
                {% for task in tasklist.open_tasks %}
                    {% if task.is_due == -1 %}
                        <tr class="danger">
                    {% elif task.is_due == 1 %}
                        <tr class="warning">
                    {% else %}
                        <tr>
                    {% endif %}

                        <td class="label_light text-center" style="border-left-color:#{{ task.triage.bg_colour }}">{{ task.local_id }}</td>
                        <td><a href="{% url 'task:view_task' task.tasklist.user.username task.local_id %}"><b>{{ task.name }}</b></a></td>

                        {% if task.due_date %}
                            <td class="human_date" title="{{ task.due_date }}">{{ task.due_date|date:"c" }}</td>
                        {% else %}
                            <td></td>
                        {% endif %}

                        <td>
                        {% if edit_permission %}
                            <div class="btn-group pull-right">
                                <a class="btn btn-sm btn-warning" href="{% url 'task:edit_task' task.tasklist.user.username task.local_id %}?next={{ current_url }}"><span class="glyphicon glyphicon-pencil"></span></a>
                                <a class="btn btn-sm btn-success" href="{% url 'task:complete_task' task.tasklist.user.username task.local_id %}?next={{ current_url }}"><span class="glyphicon glyphicon-ok-circle"></span></a>
                            </div>
                        {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot></tfoot>
            </table>
            {% else %}
                <p class="tasklist-empty-notice">No tasks!{% if edit_permission %} <a href="{% url 'task:new_task' tasklist.user.username %}?tasklist={{ tasklist.slug }}&next={{ current_url }}">New Task</a>{% endif %}</p>
        {% endif %}
        {% if tasklist.num_complete > 0 %}
            <hr>
            <h2>Closed Tasks</h2>
            <table class="table table-hover table-condensed">
                <thead>
                    <tr>
                        <th class="col-md-1 text-center">#</th>
                        <th class="col-md-7">Task</th>
                        <th class="col-md-2">Completed</th>
                        <th class="col-md-1"></th>
                    </tr>
                </thead>
                <tbody>
                {% for task in tasklist.closed_tasks %}
                    <tr>
                        <td class="label_light text-center" style="border-left-color:#{{ task.triage.bg_colour }}">{{ task.local_id }}</td>
                        <td>
                            <a href="{% url 'task:view_task' task.tasklist.user.username task.local_id %}">
                                <b>{{ task.name }}</b>
                            </a>
                        </td>

                        {% if task.completed_date %}
                            <td class="human_date" title="{{ task.completed_date }}">{{ task.completed_date|date:"c" }}</td>
                        {% else %}
                            <td></td>
                        {% endif %}

                        <td>
                        {% if edit_permission %}
                            <div class="btn-group pull-right">
                                <a class="btn btn-sm btn-danger" href="#"><span class="glyphicon glyphicon-remove"></span></a>
                            </div>
                        {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot></tfoot>
            </table>
        {% endif %}
    </div>
    <div class="col-sm-2 col-sm-pull-10">
        {% if tasklist.milestones.count > 0 %}
            <h3 class="text-center">Milestones</h3>
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th class="col-md-8">Name</th>
                        <th class="col-md-4 text-center">&#8470;</th>
                    </tr>
                </thead>
                <tbody>
                    {% for milestone in tasklist.milestones.all %}
                    <tr>
                        <td class="label_light" style="border-left-color:#{{ milestone.bg_colour }}">
                            <a href="{% url 'task:view_milestone' milestone.tasklist.user.username milestone.tasklist.slug milestone.id %}">{{ milestone.name }}</a></br>
                            <span class="human_date text-small-task" title="{{ milestone.due_date }}">{{ milestone.due_date|date:"c" }}</span>
                        </td>
                        <td class="text-center">{{ milestone.task_set.count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr/>
        {% endif %}
        {% if tasklist.tasks.count > 0 %}
            <p><b>Recently Added</b></p>
            <table class="table table-condensed">
            {% for task in recently_added %}
                <tr>
                    <td class="label_light" style="border-left-color:#{{ task.triage.bg_colour }}">{{ task.local_id }}</td>
                    <td><a href="{% url 'task:view_task' task.tasklist.user.username task.local_id %}">{{ task.name }}</a></td>
                </tr>
            {% endfor %}
            </table>
        {% endif %}
        {% if tasklist.num_complete > 0 %}
            <p><b>Recently Closed</b></p>
            <table class="table table-condensed">
            {% for task in recently_closed %}
                <tr>
                    <td class="label_light" style="border-left-color:#{{ task.triage.bg_colour }}">{{ task.local_id }}</td>
                    <td><a href="{% url 'task:view_task' task.tasklist.user.username task.local_id %}">{{ task.name }}</a></td>
                </tr>
            {% endfor %}
            </table>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/task/triages.html
{% extends "base/base.html" %}

{% block title %}Triage Categories{% endblock %}

{% block content-head-class %}head-dark{% endblock %}
{% block content-head %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>Triage Categories</h1>
            <p>Hello, {{ user.username }}, you have {{ triages.count }} triage categories:</p>
        </div>
        <div class="col-md-6">
            <div class="btn-group pull-right">
                <a class="btn btn-success" href="{% url 'task:add_triage_category' user.username %}">Add Triage Category</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<table class="table">
    <thead>
    </thead>
    <tbody>
    {% for tcat in triages %}
        <tr>
            <td style="background-color:#{{ tcat.bg_colour }}; color:#{{ tcat.fg_colour }}"><b>{{ tcat.name }}</b>
                <div class="btn-group pull-right">
                    <a class="btn btn-sm btn-warning" href="{% url 'task:edit_triage_category' user.username tcat.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
                </div>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot></tfoot>
</table>
{% endblock %}

templates/task/view.html
{% extends "base/base.html" %}
{% load markup %}

{% block title %}Task {% if not edit_permission %}{{ task.tasklist.user.username}}/{% endif %}#{{ task.local_id }} | {{ task.name }}{% endblock %}

{% block body-class %}body-task{% endblock %}
{% block content-head-class %}head-dark{% endblock %}
{% block content-head %}
<div class="container">
    <div class="row">
        <div class="col-sm-9">
            <h4>
                <a href="{% url 'task:profile' task.tasklist.user.username %}">{{ task.tasklist.user.username }}</a> / <a href="{% url 'task:view_tasklist' task.tasklist.user.username task.tasklist.slug %}">{{ task.tasklist.name }}</a> #{{ task.local_id }}
            </h4>
            <h1>{{ task.name }}</h1>
            <span class="label label-default" style="background-color:#{{ task.triage.bg_colour }}; color:#{{ task.triage.fg_colour }}">{{ task.triage.name }}</span>
        </div>
        <div class="col-sm-3">
            {% if edit_permission %}
            <div class="btn-group pull-right">
                <a class="btn btn-warning" href="{% url 'task:edit_task' task.tasklist.user.username task.local_id %}?next={{ current_url }}"><span class="glyphicon glyphicon-pencil"></span> Edit Task</a>
                {% if task.completed %}
                    <div class="btn-group pull-right">
                        <a class="btn btn-danger" href="#"><span class="glyphicon glyphicon-remove"></span></a>
                    </div>
                {% else %}
                    <div class="btn-group pull-right">
                        <a class="btn btn-success" href="{% url 'task:complete_task' task.tasklist.user.username task.local_id %}?next={{ current_url }}"><span class="glyphicon glyphicon-ok-circle"></span></a>
                    </div>
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-6">
        <legend>Description</legend>
        <div class="panel panel-info">
            <div class="panel-body panel-description">
            {% if task.description %}
                {{ task.description|markup_markdown }}
            {% else %}
                <span class="missing-property">No description</span>
            {% endif %}
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <legend>Dates</legend>
        <div class="panel panel-info">
            <table class="table">
                <tbody>
                <tr>
                    <td class="col-md-4"><b>Created</b></td>
                    <td>{{ task.creation_date }}{% if task.created_by %} by <a href="{% url 'task:profile' task.created_by.username %}">{{ task.created_by.username }}</a>{% endif %}</td>
                </tr>
                <tr>
                    <td class="col-md-4"><b>Updated</b></td>
                    <td>{{ task.modified_date }}{% if task.modified_by %} by <a href="{% url 'task:profile' task.modified_by.username %}">{{ task.modified_by.username }}</a>{% endif %}</td>
                </tr>
                <tr>
                    <td class="col-md-4"><b>Completed</b></td>
                    <td>{{ task.completed_date }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="panel panel-info">
            <table class="table">
                <tbody>
                <tr>
                    <td class="col-md-4"><b>Due</b></td>
                    {% if task.due_date %}
                    <td>{{ task.due_date }}</td>
                    {% else %}
                    <td><span class="missing-property">No due date</span></td>
                    {% endif %}
                </tr>
                <tr>
                    <td class="col-md-4"><b>Milestone</b></td>
                    {% if task.milestone %}
                    <td><a href="{% url 'task:view_milestone' task.milestone.tasklist.user.username task.milestone.tasklist.slug task.milestone.id%}"><span class="label label-default" title="{{ task.milestone.due_date }}" style="background-color:#{{ task.milestone.bg_colour }}; color:#{{ task.milestone.fg_colour }}">{{ task.milestone.name }}</span></a> {{ task.milestone.due_date }}</td>
                    {% else %}
                    <td><span class="missing-property">No milestone</span></td>
                    {% endif %}
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <legend>Links
            {% if edit_permission %}
            <a class="pull-right btn btn-sm btn-success" href="{% url 'task:link_task' task.tasklist.user.username task.local_id %}"><span class="glyphicon glyphicon-link"></span> Add Link</a></legend>
            {% endif %}
    </div>
    <div class="col-sm-6">
        {% if task.links_in.count > 0 %}
        <div class="panel panel-info">
            <table class="table">
            {% for link in task.links_in.all %}
                <tr>
                    <td>{{ link.link_type.from_desc }}</td>
                    <td>#{{ link.from_task.id }}</td>
                    <td>{{ link.from_task.name }}</td>
                </tr>
            {% endfor %}
            </table>
        </div>
        {% else %}
            <p>No incoming...</p>
        {% endif %}
    </div>
    <div class="col-sm-6">
        {% if task.links_out.count > 0 %}
        <div class="panel panel-info">
            <table class="table">
            {% for link in task.links_out.all %}
                <tr>
                    <td>{{ link.link_type.to_desc }}</td>
                    <td>#{{ link.to_task.id }}</td>
                    <td>{{ link.to_task.name }}</td>
                </tr>
            {% endfor %}
            </table>
        </div>
        {% else %}
            <p>No outgoing...</p>
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <legend>History</legend>
        {% if history %}
            {% for record in history %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ record.user.username }} @ {{ record.timestamp }}
                </div>
                <div class="panel-body">
                    {% for entry in record.get_entry_slugs %}
                        {{ entry }}
                        <br />
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        {% else %}
            <p>Nothing of interest...</p>
        {% endif %}
    </div>
</div>
{% endblock %}